###### TMUX config file ######

set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

unbind-key -T prefix C-l
unbind-key -T prefix C-h

set -s escape-time 0
# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind v split-window -h
bind s split-window -v
unbind '"'
unbind %

# open new windows in the current path
bind c new-window -c "#{pane_current_path}"

# don't rename windows automatically
set -g allow-rename off

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# switch panes using Alt-arrow without prefix
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D
# unbind h
# unbind l
# unbind k
# unbind j

bind-key L send-keys "clear" C-m

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

## Appereance
# sets refresh interval to every 5 seconds
set-option -g status-interval 5

# Setup status bar
# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"


# default window title colors
set -g window-status-format " #I #W${flags} "
set -g window-status-style fg=magenta 
set -ga window-status-current-style bg=black
set -ga window-status-current-style dim

# active window title colors
set -g window-status-current-format " #I #W${current_flags} "
set -g window-status-current-style fg=black
set -ga window-status-current-style bg=magenta
set -ga window-status-current-style bright


# pane border
set-option -g pane-border-style fg=blue
#set-option -g pane-border-fg blue
set-option -g pane-active-border-style fg=blue
#set-option -g pane-active-border-fg blue


# message text
set -g message-style fg=green
set -ga message-style bg=black


# clock
# set-window-option -g clock-mode-colour yellow


# set-option -g update-environment "SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY"


# Theme config
set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mochj
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_text "#W"

# Continuum config
set -g @continuum-restore 'on'
# set -g @continuum-save-interval '1'  # Save every 15 minutes
set -g @continuum-boot 'on'
# Resurrect config
set -g @resurrect-processes 'nvim python3'

## List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# run -b '~/.tmux/plugins/tpm/tpm'
# run -b '~/.tmux/plugins/tmux-continuum/continuum.tmux'
run -b '~/.tmux/plugins/tpm/tpm'
# run-shell '~/.tmux/plugins/tmux-continuum/continuum.tmux'
